# Generated by Django 5.0.7 on 2024-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_track_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='track_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
