# Generated by Django 5.0.7 on 2024-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_remove_track_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
